### ISSUE TITLE
How to select architectures from the trained supernet?

### ISSUE THREAD

**Issue by ranery** [changlin31/BossNAS#2]
Hi, thanks for your great work!

I tried using your given searching code for training the supernet. But I did not figure out how to search the potential architectures from such a supernet? 

I guess the validation hook serves as such functions, but I did not find the saved path information after training one epoch. Are there other files I need to explore or just waiting for more epochs to be trained?

Could you advise me about that, thanks in advance for your time and help!

Best,
Haoran

**Comment by changlin31** [comment]
Hi @ranery 

Evaluation, BatchNorm recalibration and architectures ranking are automatically performed after every training stage (default for 6 epochs). The best architecture of current stage is the top-1 encoding saved in the path rank file.

For example, our saved encodings are provided here: [https://github.com/changlin31/BossNAS/tree/main/ranking_mbconv/path_rank](https://github.com/changlin31/BossNAS/tree/main/ranking_mbconv/path_rank)
The best architecture's encoding is the combination of the first ones in each file, _i.e._ 11 0110 0111 1100 0110. (0&1 represent the first & the second candidate operation)

**Comment by ranery** [comment]
Got it, thanks for your response!

I encourage another problem when resuming the checkpoints for continually training.
````
RuntimeError: Given groups=1, weight of size 1024 512 3 3, expected input[64, 1024, 28, 28] to have 512 channels, but got 1024 channels instead
````
It occurs when it executes at:
````
if fmap_size > self.fmap_size:
  residual = self.downsample_d(x)
  x = self.conv1_d(x)
  x = self.peg_d(x)
  x = self.bn1_d(x)
````
Do you have any thoughts regarding this issue?

**Comment by changlin31** [comment]
Which code are you running? Are you searching on MBConv search space or HyTra search space?

**Comment by ranery** [comment]
Thanks for your timely response, I figured this issue out! But I find that my searched block is quite regular:
[1, 1, 1, 1] → [1, 1, 1, 1] → [0, 0, 0, 0] → [0, 0, 0, 0]

I am wondering whether do you have an explanation for this structure since it is quite different from your retrained ones.
* Why there are always four modules in one block?
* Why first eight modules are all ResConv while the last eight modules are all ResAtt?

Could you elaborate more about the rationale behind your searching methods? Specifically, how do you identify whether to conduct downsampling at current stages?

**Comment by changlin31** [comment]
- Why there are always four modules in one block?
This block partition is only used for supernet training. Different partition does not change the architecture. Your searched architecture is actually [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0].

- Why first eight modules are all ResConv while the last eight modules are all ResAtt?

**Comment by changlin31** [comment]
We have now add the restriction to avoid the case of downsampling across multiple scale. Hope this can solve the problem.

**Comment by ranery** [comment]
Thanks for your clarification!
