### ISSUE TITLE
How to re-train the model of BossNAS-M1 and M2

### ISSUE THREAD

**Issue by Jxu-Thu** [changlin31/BossNAS#3]
Thanks for your great codes!
Do you provide the codes to re-train the model on the MobileNet? such as BossNAS-M1 and M2

**Comment by changlin31** [comment]
Thank you.

We use timm ([https://github.com/rwightman/pytorch-image-models](https://github.com/rwightman/pytorch-image-models)) to train our BossNAS-M models. Code for BossNAS-M models will be released in the future.
