### ISSUE TITLE
About formulation (1) and (6)

### ISSUE THREAD

**Issue by NickChang97** [changlin31/BossNAS#5]
Hi, very thanks for sharing your nice work. In the paper's formulation (1) and (6)， all has λ_k. But it seems to be no explaination about them. Could you please point it out here.

**Comment by changlin31** [comment]
`λ_k` represent the weighting factor (a hyperparameter) to balance the loss of different blocks. These factors are set to 1 in this work and our previous work [36] and is learnable in DONNA [45].

**Comment by NickChang97** [comment]
Really thanks for your reply.
