### ISSUE TITLE
How you calculate the MACs?

### ISSUE THREAD

**Issue by ranery** [changlin31/BossNAS#6]
Hi, 

I have another question about MACs. Could you elaborate on how you calculate that? Thanks.

Best

**Comment by ranery** [comment]
Hi, have you noticed this question? Current, my measurement about BossNAS-T0 is consistent with your reported 3.4G MACs, while my measurement about Bossnet-T1 is 7.62G, slightly less than your reported 7.9B MACs.

I want to confirm with you about the MACs measurement details if it is convenient for you.

**Comment by changlin31** [comment]
Hi, sorry for the delay. I just uploaded the MAdds calculation file:
https://github.com/changlin31/BossNAS/blob/2e6ff17737b8546dcc06b4bfb3c690f6e1290767/retraining_hytra/boss_madds.py
