### ISSUE TITLE
Some questions about the code and paper.

### ISSUE THREAD

**Issue by zhy0860** [changlin31/BossNAS#8]
Hi, great work!

I have some question about the code and paper:

1. In section 3.3 of the paper which is about the searching phase, when calculating the evaluation loss in equation(5) and (6) the probability ensemble of the architecture population is from the online network, but in the code it's from the target network, which makes me confused.

2. Still in section 3.3, it is mentioned that the searching are with an evolutionary algorithm, I read the references[12] and [54] but still have no clue how the evolutionary algorithm is implemented in the code, to be specific, how the architecture population is evolved?

3. In the code of hytra_supernet.py, the stage depths are set to [4,3,2,2], is there a particular reason to set so? why not use [4,4,4,4] so that all possible pathes can be chosen?

Thanks a lot for your time and I'm looking forward to your reply!

**Comment by changlin31** [comment]
Hi @zhy0860 , thanks for your interest!

1. Sorry for the confusion. In Eq. (5) and (6), the notation _**S**_ is only used to denote that we only use one single network (either online or the target) for evaluation loss, in contrast to the training stage, where a pair of siamese networks are used. In practice, the target network usually have better performance. So we directly use it as our supernet for eval. (In self-supervised learning, it's also common to use the target network for evaluation results)

2. We don't use EA as our search space is small enough for extensive traversal search, in each stage, as mentioned in the paper:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/61453811/142573212-57b4b9e6-6812-4a9e-af1d-6f0e6eaa61c8.png">

3. This is just a heuristic setting to reduce the search space. You can set them back to [4,4,4,4] if you want to explore the whole search space. Actually, these networks with larger scales is not likely to be chosen even if the whole search space is enabled.

**Comment by zhy0860** [comment]
Appreciate it so much for your answer! It helps a lot.
